### ISSUE TITLE
Can GDriveFS mount on a Headless system

### ISSUE THREAD

**Issue by pageauc** [dsoprea/GDriveFS#131]
Trying to mount GDriveFS on a Raspberry PI as a background process but the network connection fails.  Is there a way to have GDriveFS reliably mounted as a background daemon via a user or /etc/init.d script?

**Comment by arniotis** [comment]
I'm using it on a raspberry pi. Just 
- configure it under the root account:
````
$ sudo -i
$ gdfstool auth -u
$ gdfstool auth -a
````
then add gdfs to the bottom of your /etc/rc.local file. If your network takes a while to start (say, you are behind a VPN), you might also want to delay the execution of the command a bit:

````
sleep 60
/usr/local/bin/gdfs /path/to/cred /path/to/mount
`````

I have GD_DEBUG permanently enabled because of what I describe in issue #132 

````
sleep 60
GD_DEBUG=1  /usr/local/bin/gdfs /path/to/cred /path/to/mount > /dev/null 2> /dev/null &
`````

Cheers

Michael

**Comment by pageauc** [comment]
Hi Michael

Thanks very much for your reply.  I have found a version of drive at
https://github.com/odeke-em/drive

Here are the steps I took to install the precompiled Rapberry Pi arm binary
to my RPI's

cd /tmp
wget
https://github.com/odeke-em/drive/releases/download/v0.2.2-arm-binary/drive-arm-binary
chmod +x drive-arm-binary
sudo cp drive-arm-binary /usr/local/bin/gdrive
cd ~
gdrive version

cd pi-timolo
gdrive init

copied and pasted url to chrome browser then copied pasted security token
back to rpi to complete init process.
this created a hidden folder containing credentials into pi-timolo called
.gd

Then did a push and after a long resolve time it did a sync of the
specified folder. Still looking at various other gdrive options.
sudo gdrive push -no-prompt ./dogcam/*jpg

This version seems to have more features and was easy to install for me per
above.

I have written a script than only does a sync if my program has updated
data.  This avoids unnecessary hand shaking and is working fine.

I will test your version as well.

Thanks
Claude ...


On Mon, Jun 1, 2015 at 4:10 AM, Michael <notifications@github.com> wrote:

> I'm using it on a raspberry pi. Just
>
>    - configure it under the root account:
>
> $ sudo -i
> $ gdfstool auth -u
> $ gdfstool auth -a
>
> then add gdfs to the bottom of your /etc/rc.local file. If your network
> takes a while to start (say, you are behind a VPN), you might also want to
> delay the execution of the command a bit:
>
> sleep 60
> /usr/local/bin/gdfs /path/to/cred /path/to/mount
>
> I have GD_DEBUG permanently enabled because of what I describe in issue
> #132 <https://github.com/dsoprea/GDriveFS/issues/132>
>
> sleep 60
> GD_DEBUG=1  /usr/local/bin/gdfs /path/to/cred /path/to/mount > /dev/null 2> /dev/null &
>
> Cheers
>
> Michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dsoprea/GDriveFS/issues/131#issuecomment-107354241>.
>



-- 
See my YouTube Channel at http://www.youtube.com/user/pageaucp

**Comment by dsoprea** [comment]
You may or may not find whether this works for your use-case as a background process. Since GD requires frequent reauthentication, which is done automatically as long as you're still mounted, you wouldn't normally notice. However, you might find that, if your system is down or otherwise unmounted for a sufficient amount of time, it may no longer mount on the way up.
