### ISSUE TITLE
mime type not set correctly

### ISSUE THREAD

**Issue by BrendenCA** [dsoprea/GDriveFS#160]
Hello @dsoprea 

I have been uploading a couple of MKV video files and they are being uploaded with mimetype=application/octet-stream Which is incorrect.

The uploaded data is still there and valid, the only issue is I am unable to preview the file online ( drive.google.com ) because google drive has the wrong mime type.

If mime_type is set to None, then google drive will automatically determine the mime type from the uploaded content.
Source: https://developers.google.com/drive/v2/reference/files/insert#request-body

I have tried commenting line 513 in drive.py and it seems to have worked.
https://github.com/dsoprea/GDriveFS/blob/master/gdrivefs/gdtool/drive.py#L513

**Comment by dsoprea** [comment]
So, I'm just going to take a moment and expound on how to control mimetype derivation in GDFS.

The typing process works as follows (starting [here](https://github.com/dsoprea/GDriveFS/blob/master/gdrivefs/gdfs/gdfuse.py#L292)):
1. The split_path call dissects the file-path argument. You can pass an optional type-hint in the way of a mime-type (e.g. "Biola.docx#application+pdf")
2. We call mimetypes.guess_type() from Python.
3. Fallback to taking the value of the `default_mimetype` configurable ("application/octet-stream").

I had also added the ability to read a JSON-encoded dictionary of file-extension/mime-type mappings back in the very beginning, but it looks like this was never wired in. I guess it never came up. I've gone ahead and implemented this between steps (1) and (2). I committed this to the "mimetype_overrides" branch. If you could test it, I'd appreciate it. It's getting pretty late but I wanted to throw it out there for you without waiting, just in case you wanted it. In order to use this, pass it as an "o" option in the mount command: e.g. "-o extension_mapping_filepath=/home/dustin/gdfs_mimetypes.json". By default, the file-path is "/etc/gdfs/extension_mapping.json" but it is obviously only used if it exists.

Finally, the least-elegant option is to add an entry to the mime-type/extension dictionary (`default_extensions`) at the top of the `_DriveUtility` class, at the top of `utility.py`. 

Now, as far as that default-mimetype" option that you commented it can *also* be overridden like any other option (like the above) by passing it in the mount options and assign it ("file_default_mime_type") some other value. Note that I just committed another change that will make it `None` if you set it to empty.

I'd appreciate you testing both of these changes and getting back to me. I'll totally deimplement the default-mimetype logic. I'll have to do this a little later, but it'd be great if *you* could do this and submit a PR. Your choice. 

Thanks.

**Comment by BrendenCA** [comment]
Hi, But i dont understand why dont we just leave the mime type empty and let google do its thing? Google Drive will automatically figure out the mime type from the uploaded data.

Incase a user wants to force a Mime type to a extension then he can use the dictionary function.

The call to mimetypes.guess_type()  is not required.

In summary,
While uploading we set the mime type to None. ( or to a value from Dictionary if the user specifies the json Dictionary )

**Comment by BrendenCA** [comment]
Hey please disregard my previous comment, didnt understand what was going on.

Anyways in regards to the JSON-encoded dictionary,
I Just realised that this can be accomplished by using user defined mime types https://help.ubuntu.com/community/AddingMimeTypes

**Comment by dsoprea** [comment]
I've removed a default mimetype for uploads. I've also deimplemented `mimetypes.guess_type()` since I've never been particularly impressed by the guesses. In light of the fact that you don't need to provide a mimetype I'd rather not keep a half-hearted guess that ends up screwing anyone anyways. You can use the type-hinting feature by appending the mime-type to the filename as previously indicated (is probably usually the most intuitive/direct route) as well as using the dictionary as a longer-term solution if Google doesn't quess correctly either.

I've applied the update, tested, and committed. Let me know if this is still an issue for you.
