### ISSUE TITLE
Revisit Unicode filenames

### ISSUE THREAD

**Issue by dsoprea** [dsoprea/GDriveFS#2]
We were having trouble returning Unicode filenames in readdir(), but it seems like other people may not be having that problem.

**Comment by abriel** [comment]
Hello,

I also run into this issue.
On my drive I created a test folder with a few files.
How it looks like via gfds mount:
```bash
[spirit@eternal nonasciitest]$ ls -lah
ls: cannot access тест1#: Input/output error
total 0
drwxrwxrwx 2 spirit users 4.0K янв 30 14:26 .
drwxrwxrwx 2 spirit users 4.0K авг 13 02:14 ..
-rw-rw-rw- 1 spirit users 1000 янв 30 14:26 test1#
-????????? ? ?      ?        ?            ? тест1#
```

Here is what gdfs tells running with -d arg:
```bash
unique: 439, opcode: LOOKUP (1), nodeid: 62, insize: 51, pid: 23752
LOOKUP /nonasciitest/тест1#
getattr /nonasciitest/тест1#
   unique: 439, error: -5 (Input/output error), outsize: 16
unique: 440, opcode: LOOKUP (1), nodeid: 62, insize: 47, pid: 23752
LOOKUP /nonasciitest/test1#
getattr /nonasciitest/test1#
   NODEID: 63
   unique: 440, success, outsize: 144
```

I am guessing the root of the issue may be in some library from the dependence list.
Will be glad to help you with debugging.

Thanks.

**Comment by psmelion** [comment]
Thanks for the great software! :)

I was using google-drive-ocamlfuse. But it seems to lost connection after idling the system for a few hours. So I try GDriveFS. During the installation, I had to fix/install many dependencies. And finally I have it up and running!

All works fine in console. In a ssh session, I can see all my unicode filename on Google Drive.

But all unicode filename disappeared via Samba share to a Windows 7 PC, as if the file doesn't exist! My main purpose of setting up a mounted Google Drive on a Linux is to share the mount to a Windows PC.

On the other hand, while using google-drive-ocamlfuse, the same Samba share works perfectly fine with unicode filename on Windows.

Any hints to solve this? Otherwise I couldn't really use this! Thanks!

**Comment by agusdallalba** [comment]
@psmelion: Replace [line 94 of `gdfs/fsutility.py`](https://github.com/dsoprea/GDriveFS/blob/master/gdrivefs/gdfs/fsutility.py#L94) from `path.encode('ASCII'))` to `path.encode('UTF-8'))`.

You can find that file wherever gdrivefs is installed. In my case it was in `/usr/lib/python2.7/site-packages/gdrivefs/` but it may depend on your distribution.

**Comment by dsoprea** [comment]
@agusdallalba I've been trying to fix this, but I suspect there are issues
with the library that I'm using in irder to act as a filesystem. It's also
complicated by the fact that I don't use characters beyond ASCII.. It's
difficult to test.

To what extent does making this one change fix anything?

**Comment by psmelion** [comment]
@agusdallalba:

WOW! It actually works!!! THANKS! Mine is Ubuntu and the fsutility.py is under /usr/local/python2.7/site-packages/gdrivefs/

Now off to actually use it...

**Comment by agusdallalba** [comment]
@dsoprea: Sorry I took so long to reply. That change fixes everything in my side with no side effects from can see. Are you using a UTF-8 locale? The enviroment variable $LANG should be 'en_US.utf8' or similar. Sometimes when setting up a machine I forget to set the locale and this kind of things break all over the place.

**Comment by reacocard** [comment]
Fix works for me too, thanks!

**Comment by dsoprea** [comment]
I added the fix. Please upgrade and test.

**Comment by dsoprea** [comment]
No problem here.
